from ..conftest import FIXTURES_FOLDER

RBHTFINDER_FIXTURES_FOLDER = FIXTURES_FOLDER / "rbhtfinder"
EXPECTED_OUTPUT_FILE = str(RBHTFINDER_FIXTURES_FOLDER / "output.txt")
RESULT_OUTPUT_FILE = str(RBHTFINDER_FIXTURES_FOLDER / "original_output.txt")
