from ..conftest import FIXTURES_FOLDER

SDRMSD_FIXTURES_FOLDER = FIXTURES_FOLDER / "sdtether"
REF_FILE = str(SDRMSD_FIXTURES_FOLDER / "ref.sdf")
INPUT_FILE = str(SDRMSD_FIXTURES_FOLDER / "ref.sdf")
EXPECTED_OUTPUT_FILE_1 = str(SDRMSD_FIXTURES_FOLDER / "out.sdf")