from ..conftest import FIXTURES_FOLDER

SDTETHER_FIXTURES_FOLDER = FIXTURES_FOLDER / "sdtether"
REF_FILE = str(SDTETHER_FIXTURES_FOLDER / "ref.sdf")
INPUT_FILE = str(SDTETHER_FIXTURES_FOLDER / "ref.sdf")
EXPECTED_OUTPUT_FILE_1 = str(SDTETHER_FIXTURES_FOLDER / "out.sdf")
