#!/usr/bin/env python3

# remove this script when the first script is migrated here
# actual code for the scripts should be in rdock_utils.<dedicated_script_name_module>
# for example,
# from rdock_utils.sdsort import main

# From apps
from rdock_utils.sdnothing import main

if __name__ == "__main__":
    main()
