on:
  workflow_call:
    inputs:
      distribution:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build base image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: rdock-${{ inputs.distribution }}:base
        file: .github/docker/Dockerfile.${{ inputs.distribution }}
        target: base
        cache-from: type=gha,scope=${{ inputs.distribution }}
        cache-to: type=gha,mode=max,scope=${{ inputs.distribution }}
        load: true

    - name: Build rDock
      run: docker run --rm -v $PWD:/rdock -w /rdock rdock-${{ inputs.distribution }}:base make -j 2
    
    - name: Test rDock
      run: docker run --rm -v $PWD:/rdock -w /rdock rdock-${{ inputs.distribution }}:base make test