name: [rdock-utils] Lint and Test

defaults:
  run:
    working-directory: ./rdock-utils

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build rdock-utils dev image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: ghcr.io/rdock-utils:dev
        file: ./Dockerfile
        target: development
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true

  test:
    needs: build-dev
    runs-on: ubuntu-latest
    container: ghcr.io/rdock-utils:dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run flake8
        run: flake8 .

      - name: Run black
        run: black --check .

      - name: Run isort
        run: isort --check .

      - name: Run mypy
        run: mypy .

      - name: Run pytest
        run: pytest -v .
