name: "[rdock-utils] Lint and Test"

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build rdock-utils dev image
      uses: docker/build-push-action@v5
      with:
        context: ./rdock-utils
        tags: ghcr.io/cbdd/rdock-utils:dev
        file: ./rdock-utils/Dockerfile
        target: development
        cache-from: type=gha,scope=rdock-utils
        cache-to: type=gha,mode=max,scope=rdock-utils
        load: true

    - name: flake8
      run: docker run --rm -v $PWD/rdock-utils:/rdock-utils -w /rdock-utils ghcr.io/cbdd/rdock-utils:dev flake8 .

    - name: black
      run: docker run --rm -v $PWD/rdock-utils:/rdock-utils -w /rdock-utils ghcr.io/cbdd/rdock-utils:dev black --check .

    - name: isort
      run: docker run --rm -v $PWD/rdock-utils:/rdock-utils -w /rdock-utils ghcr.io/cbdd/rdock-utils:dev isort --check .
    
    - name: mypy
      run: docker run --rm -v $PWD/rdock-utils:/rdock-utils -w /rdock-utils ghcr.io/cbdd/rdock-utils:dev mypy .
